### ISSUE TITLE
No. of objects in "X-0.5.0.fits and "X-targetdb-0.5.0.fits" ? 

### ISSUE THREAD

**Issue by BGaensicke** [sdss/target_selection#59]
Should the number of objects in the two file flavours for a given carton, be identical? They almost always are, but 

mwm_cb_300pc_apogee-0.5.0.fits -> 89492 objects
mwm_cb_300pc_apogee-targetdb-0.5.0.fits -> 85846 objects

**Comment by albireox** [comment]
@BGaensicke Yes, it seems there was a discrepancy. I rerun the cartons and regenerated the files in the server. They now match with 85846 targets. Please have a look.

The discrepancy was because the extra number of targets in `mwm_cb_300pc_apogee-0.5.0.fits` have `selected=False`. That's a condition that allows to select targets from a SQL query but then restrict the ones that really make it with a post-process. This carton should not have those `selected=False` so I'm not sure why they appeared in the original file. In any case, check the new files and let me know if there are other issues.

BTW, while rerunning these I noticed that the CB APOGEE cartons select stars with H<11 but the BOSS ones include everything. Are the BOSS cartons meant to be H>11? That was not super clear in the wiki page. That affects all the CB BOSS cartons.

**Comment by BGaensicke** [comment]
Yes, that is correct: we want to get optical spectra for all targets, and IR spectra for those that are sufficiently bright in the H-band. I added that comment to the Wiki page.

**Comment by albireox** [comment]
Excellent, thanks for checking.
